"""empty message

Revision ID: 17550ddcc838
Revises: d0045e9bd751
Create Date: 2026-03-25 15:47:18.420289

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "17550ddcc838"
down_revision: Union[str, Sequence[str], None] = "d0045e9bd751"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("google_id", sa.String(), nullable=True))
    op.add_column("users", sa.Column("github_id", sa.String(), nullable=True))
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_unique_constraint(None, "users", ["email"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_index(
        op.f("ix_users_username"), "users", ["username"], unique=True
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.alter_column(
        "users", "email", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("users", "github_id")
    op.drop_column("users", "google_id")
    # ### end Alembic commands ###
