"""empty message

Revision ID: 2674194c1824
Revises: 2efb958ae7f4
Create Date: 2026-03-30 16:28:34.762115

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2674194c1824"
down_revision: Union[str, Sequence[str], None] = "2efb958ae7f4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("current_language_pair_id", sa.Integer(), nullable=True),
    )
    op.create_foreign_key(
        None,
        "users",
        "language_pairs",
        ["current_language_pair_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "current_language_pair_id")
    # ### end Alembic commands ###
