"""empty message

Revision ID: 976805326bba
Revises: 2674194c1824
Create Date: 2026-04-02 20:48:40.101402

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "976805326bba"
down_revision: Union[str, Sequence[str], None] = "2674194c1824"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "languages", sa.Column("demo_code", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("languages", "demo_code")
    # ### end Alembic commands ###
