"""empty message

Revision ID: d0f8fe8a1161
Revises: 17550ddcc838
Create Date: 2026-03-26 20:55:57.694525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d0f8fe8a1161"
down_revision: Union[str, Sequence[str], None] = "17550ddcc838"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "languages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("slug", sa.String(length=50), nullable=False),
        sa.Column("extension", sa.String(length=10), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("extension"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "language_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lang1_id", sa.Integer(), nullable=False),
        sa.Column("lang2_id", sa.Integer(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "lang1_id < lang2_id", name="check_language_pair_order"
        ),
        sa.ForeignKeyConstraint(
            ["lang1_id"], ["languages.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["lang2_id"], ["languages.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "lang1_id", "lang2_id", name="unique_language_pair"
        ),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "user_language_pairs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("pair_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"], ["language_pairs.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_language_pairs")
    op.drop_table("language_pairs")
    op.drop_table("languages")
    # ### end Alembic commands ###
